export const actionTypes = {
    MY_PROFILE: "MY_PROFILE",
    // TAMAN HERBAL PLANT
    TAMAN_HERBAL_LIST: "TAMAN_HERBAL_LIST",
    // TAMAN HERBAL HERO
    TAMAN_HERBAL_HERO: "TAMAN_HERBAL_HERO",
    
    //START USER MANAGEMENT ACTIONS TYPE
    LIST_USER_CUSTOMER: "LIST_USER_CUSTOMER",
    LIST_USER_ADMIN: "LIST_USER_ADMIN",
    USER_CUSTOMER_TOTAL: "USER_CUSTOMER_TOTAL",
    LIST_ROLES: "LIST_ROLES",
    //END USER MANAGEMENT ACTIONS TYPE

    //START GENERAL SETTING ACTIONS TYPE
    TERMS_AND_CONDITIONS: "TERMS_AND_CONDITIONS",
    SINGLE_LINK: "SINGLE_LINK",
    LIST_CAMPAIGN_BANNER: "LIST_CAMPAIGN_BANNER",
    FAQ_STATE: "FAQ_STATE",
    // END GENERAL SETTING ACTIONS TYPE

    //START FACTORIES ACTIONS TYPE
    FACTORIES_LIST: "FACTORIES_LIST",
    ROOM_LIST: "ROOM_LIST",
    ROOM_MASTER: "ROOM_MASTER",
    LIST_GALERIES: "LIST_GALERIES",
    //END FACTORIES ACTIONS TYPE

    // START MASTER DATA
    MASTER_PRODUCT: "MASTER_PRODUCT",
    MASTER_PACKAGE: "MASTER_PACKAGE",
    MASTER_FOOD: "MASTER_FOOD",
    MASTER_TYPE_IDENTITY: "MASTER_TYPE_IDENTITY",
    MASTER_SETTINGS: "MASTER_SETTINGS",
    // END MASTER DATA

    // START LOG TRANSACTIONS
    AUDIT_TRAIL: "AUDIT_TRAIL",
    BALANCE: "BALANCE",
    // END LOG TRANSACTIONS

    // START HUMAN RESOURCE
    LIST_JOB_PORTAL: "LIST_JOB_PORTAL",
    LIST_APPLICANTS: "LIST_APPLICANTS",
    // END HUMAN RESOURCE

    // START LOCATION
    LIST_PROVINCE: "LIST_PROVINCE",
    // END LOCATION

    // UNTUK LATIHAN
    LIST_MOBIL: "LIST_MOBIL",
    TOTAL_MOBIL: "TOTAL_MOBIL"
    
}